env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/functional-parameters: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
